### ISSUE TITLE
You should use the GifMe API vs Giphy

### ISSUE THREAD

**Issue by DrewDahlman** [OfficeDev/Outlook-Add-in-GifMe#1]
https://github.com/GifMe/GifMeApi

**Comment by martellaj** [comment]
Awesome name, @DrewDahlman! I'm a little disappointed what I thought was a unique name was already used. I'll check out your API and see if I'd gain anything by swapping it in for Giphy.

**Comment by DrewDahlman** [comment]
haha :+1: 

biggest difference is that all of the gifs from the api are user generated and constantly growing, also it's a natural language engine so it has better results.
